export const alumniData = [
  {
    id: "cse1",
    src: require("./images/Manoj.jpg"),
    name: "Manoj",
    phone: "6384554049",
    location: "Salem",
    year: "2021",
    company: "Tidal Park",
    email: "manoj123@gmail.com",
    skills: "C++,JAVA,PYTHON,C",
    eventsParticipated: "Smart india hackathon",
    platforms: "Leetcode,HackerRank,HackerEarth",
    achievements:
      "A Unicorn developer, first to be certified by TidalPark as Associate Android Developer in the world, Droidcon Speaker, a regular blogger at Medium and an open source contributor.Demonstrated the ability to handle both design and development in an efficient way. Accomplishments and Recognition, First to be certified as Android Developer by Tidalpark, Full Sponsorship by Tidalpark for io17, Droidcon Boston Speaker, GDG community Speaker, Mentor at Mindorks",
    contest: "LeetCode, CodingNinjas",
  },
  {
    id: "cse2",
    src: require("./images/Shridhar.jpg"),
    name: "Shridhar",
    phone: "6384554049",
    location: "Chennai",
    year: "2021",
    company: "Amazon",
    email: "manoj123@gmail.com",
    skills: "C++,JAVA,PYTHON,C",
    eventsParticipated: "Smart india hackathon",
    platforms: "Leetcode,HackerRank,HackerEarth",
    achievements:
      "A Unicorn developer, first to be certified by TidalPark as Associate Android Developer in the world, Droidcon Speaker, a regular blogger at Medium and an open source contributor.Demonstrated the ability to handle both design and development in an efficient way. Accomplishments and Recognition, First to be certified as Android Developer by Tidalpark, Full Sponsorship by Tidalpark for io17, Droidcon Boston Speaker, GDG community Speaker, Mentor at Mindorks",
    contest: "LeetCode, CodingNinjas",
  },
  {
    id: "cse3",
    src: require("./images/Selva.png"),
    name: "Selva",
    phone: "6384554049",
    location: "Salem",
    year: "2021",
    company: "Tidal Park",
    email: "manoj123@gmail.com",
    skills: "C++,JAVA,PYTHON,C",
    eventsParticipated: "Smart india hackathon",
    platforms: "Leetcode,HackerRank,HackerEarth",
    achievements:
      "A Unicorn developer, first to be certified by TidalPark as Associate Android Developer in the world, Droidcon Speaker, a regular blogger at Medium and an open source contributor.Demonstrated the ability to handle both design and development in an efficient way. Accomplishments and Recognition, First to be certified as Android Developer by Tidalpark, Full Sponsorship by Tidalpark for io17, Droidcon Boston Speaker, GDG community Speaker, Mentor at Mindorks",
    contest: "LeetCode, CodingNinjas",
  },
  {
    id: "cse4",
    src: require("./images/Rajesh.jpg"),
    name: "Rajesh",
    phone: "6384554049",
    location: "Salem",
    year: "2021",
    company: "Tidal Park",
    email: "manoj123@gmail.com",
    skills: "C++,JAVA,PYTHON,C",
    eventsParticipated: "Smart india hackathon",
    platforms: "Leetcode,HackerRank,HackerEarth",
    achievements:
      "A Unicorn developer, first to be certified by TidalPark as Associate Android Developer in the world, Droidcon Speaker, a regular blogger at Medium and an open source contributor.Demonstrated the ability to handle both design and development in an efficient way. Accomplishments and Recognition, First to be certified as Android Developer by Tidalpark, Full Sponsorship by Tidalpark for io17, Droidcon Boston Speaker, GDG community Speaker, Mentor at Mindorks",
    contest: "LeetCode, CodingNinjas",
  },
  {
    id: "cse5",
    src: require("./images/Divya.jpg"),
    name: "Divya",
    phone: "6384554049",
    location: "Salem",
    year: "2021",
    company: "Tidal Park",
    email: "manoj123@gmail.com",
    skills: "C++,JAVA,PYTHON,C",
    eventsParticipated: "Smart india hackathon",
    platforms: "Leetcode,HackerRank,HackerEarth",
    achievements:
      "A Unicorn developer, first to be certified by TidalPark as Associate Android Developer in the world, Droidcon Speaker, a regular blogger at Medium and an open source contributor.Demonstrated the ability to handle both design and development in an efficient way. Accomplishments and Recognition, First to be certified as Android Developer by Tidalpark, Full Sponsorship by Tidalpark for io17, Droidcon Boston Speaker, GDG community Speaker, Mentor at Mindorks",
    contest: "LeetCode, CodingNinjas",
  },
  {
    id: "cse6",
    src: require("./images/saru.jpg"),
    name: "Saru",
    phone: "6384554049",
    location: "Salem",
    year: "2021",
    company: "Tidal Park",
    email: "manoj123@gmail.com",
    skills: "C++,JAVA,PYTHON,C",
    eventsParticipated: "Smart india hackathon",
    platforms: "Leetcode,HackerRank,HackerEarth",
    achievements:
      "A Unicorn developer, first to be certified by TidalPark as Associate Android Developer in the world, Droidcon Speaker, a regular blogger at Medium and an open source contributor.Demonstrated the ability to handle both design and development in an efficient way. Accomplishments and Recognition, First to be certified as Android Developer by Tidalpark, Full Sponsorship by Tidalpark for io17, Droidcon Boston Speaker, GDG community Speaker, Mentor at Mindorks",
    contest: "LeetCode, CodingNinjas",
  },
  {
    id: "aids1",
    src: require("./images/Abinaya.jpg"),
    name: "Abinaya",
    phone: "6384554049",
    location: "Salem",
    year: "2021",
    company: "Tidal Park",
    email: "manoj123@gmail.com",
    skills: "C++,JAVA,PYTHON,C",
    eventsParticipated: "Smart india hackathon",
    platforms: "Leetcode,HackerRank,HackerEarth",
    achievements:
      "A Unicorn developer, first to be certified by TidalPark as Associate Android Developer in the world, Droidcon Speaker, a regular blogger at Medium and an open source contributor.Demonstrated the ability to handle both design and development in an efficient way. Accomplishments and Recognition, First to be certified as Android Developer by Tidalpark, Full Sponsorship by Tidalpark for io17, Droidcon Boston Speaker, GDG community Speaker, Mentor at Mindorks",
    contest: "LeetCode, CodingNinjas",
  },
  {
    id: "aids2",
    src: require("./images/mithuna.jpg"),
    name: "Mithuna",
    phone: "6384554049",
    location: "Salem",
    year: "2021",
    company: "Tidal Park",
    email: "manoj123@gmail.com",
    skills: "C++,JAVA,PYTHON,C",
    eventsParticipated: "Smart india hackathon",
    platforms: "Leetcode,HackerRank,HackerEarth",
    achievements:
      "A Unicorn developer, first to be certified by TidalPark as Associate Android Developer in the world, Droidcon Speaker, a regular blogger at Medium and an open source contributor.Demonstrated the ability to handle both design and development in an efficient way. Accomplishments and Recognition, First to be certified as Android Developer by Tidalpark, Full Sponsorship by Tidalpark for io17, Droidcon Boston Speaker, GDG community Speaker, Mentor at Mindorks",
    contest: "LeetCode, CodingNinjas",
  },
  {
    id: "aids3",
    src: require("./images/sharmi.jpg"),
    name: "Sharmila",
    phone: "6384554049",
    location: "Salem",
    year: "2021",
    company: "Tidal Park",
    email: "manoj123@gmail.com",
    skills: "C++,JAVA,PYTHON,C",
    eventsParticipated: "Smart india hackathon",
    platforms: "Leetcode,HackerRank,HackerEarth",
    achievements:
      "A Unicorn developer, first to be certified by TidalPark as Associate Android Developer in the world, Droidcon Speaker, a regular blogger at Medium and an open source contributor.Demonstrated the ability to handle both design and development in an efficient way. Accomplishments and Recognition, First to be certified as Android Developer by Tidalpark, Full Sponsorship by Tidalpark for io17, Droidcon Boston Speaker, GDG community Speaker, Mentor at Mindorks",
    contest: "LeetCode, CodingNinjas",
  },
  {
    id: "aids4",
    src: require("./images/Priya.jpg"),
    name: "Priya",
    phone: "6384554049",
    location: "Salem",
    year: "2021",
    company: "Tidal Park",
    email: "manoj123@gmail.com",
    skills: "C++,JAVA,PYTHON,C",
    eventsParticipated: "Smart india hackathon",
    platforms: "Leetcode,HackerRank,HackerEarth",
    achievements:
      "A Unicorn developer, first to be certified by TidalPark as Associate Android Developer in the world, Droidcon Speaker, a regular blogger at Medium and an open source contributor.Demonstrated the ability to handle both design and development in an efficient way. Accomplishments and Recognition, First to be certified as Android Developer by Tidalpark, Full Sponsorship by Tidalpark for io17, Droidcon Boston Speaker, GDG community Speaker, Mentor at Mindorks",
    contest: "LeetCode, CodingNinjas",
  },
  {
    id: "it1",
    src: require("./images/Kavipriya.jpg"),
    name: "Kavipriya",
    phone: "6384554049",
    location: "Salem",
    year: "2021",
    company: "Tidal Park",
    email: "manoj123@gmail.com",
    skills: "C++,JAVA,PYTHON,C",
    eventsParticipated: "Smart india hackathon",
    platforms: "Leetcode,HackerRank,HackerEarth",
    achievements:
      "A Unicorn developer, first to be certified by TidalPark as Associate Android Developer in the world, Droidcon Speaker, a regular blogger at Medium and an open source contributor.Demonstrated the ability to handle both design and development in an efficient way. Accomplishments and Recognition, First to be certified as Android Developer by Tidalpark, Full Sponsorship by Tidalpark for io17, Droidcon Boston Speaker, GDG community Speaker, Mentor at Mindorks",
    contest: "LeetCode, CodingNinjas",
  },
  {
    id: "it2",
    src: require("./images/Krishna.jpg"),
    name: "Krishna",
    phone: "6384554049",
    location: "Salem",
    year: "2021",
    company: "Tidal Park",
    email: "manoj123@gmail.com",
    skills: "C++,JAVA,PYTHON,C",
    eventsParticipated: "Smart india hackathon",
    platforms: "Leetcode,HackerRank,HackerEarth",
    achievements:
      "A Unicorn developer, first to be certified by TidalPark as Associate Android Developer in the world, Droidcon Speaker, a regular blogger at Medium and an open source contributor.Demonstrated the ability to handle both design and development in an efficient way. Accomplishments and Recognition, First to be certified as Android Developer by Tidalpark, Full Sponsorship by Tidalpark for io17, Droidcon Boston Speaker, GDG community Speaker, Mentor at Mindorks",
    contest: "LeetCode, CodingNinjas",
  },
  {
    id: "it3",
    src: require("./images/Nirmala.jpg"),
    name: "Nirmala",
    phone: "6384554049",
    location: "Salem",
    year: "2021",
    company: "Tidal Park",
    email: "manoj123@gmail.com",
    skills: "C++,JAVA,PYTHON,C",
    eventsParticipated: "Smart india hackathon",
    platforms: "Leetcode,HackerRank,HackerEarth",
    achievements:
      "A Unicorn developer, first to be certified by TidalPark as Associate Android Developer in the world, Droidcon Speaker, a regular blogger at Medium and an open source contributor.Demonstrated the ability to handle both design and development in an efficient way. Accomplishments and Recognition, First to be certified as Android Developer by Tidalpark, Full Sponsorship by Tidalpark for io17, Droidcon Boston Speaker, GDG community Speaker, Mentor at Mindorks",
    contest: "LeetCode, CodingNinjas",
  },
  {
    id: "it4",
    src: require("./images/Naveen.jpg"),
    name: "Naveen",
    phone: "6384554049",
    location: "Salem",
    year: "2021",
    company: "Tidal Park",
    email: "manoj123@gmail.com",
    skills: "C++,JAVA,PYTHON,C",
    eventsParticipated: "Smart india hackathon",
    platforms: "Leetcode,HackerRank,HackerEarth",
    achievements:
      "A Unicorn developer, first to be certified by TidalPark as Associate Android Developer in the world, Droidcon Speaker, a regular blogger at Medium and an open source contributor.Demonstrated the ability to handle both design and development in an efficient way. Accomplishments and Recognition, First to be certified as Android Developer by Tidalpark, Full Sponsorship by Tidalpark for io17, Droidcon Boston Speaker, GDG community Speaker, Mentor at Mindorks",
    contest: "LeetCode, CodingNinjas",
  },
  {
    id: "it5",
    src: require("./images/Monisha.jpg"),
    name: "Monisha",
    phone: "6384554049",
    location: "Salem",
    year: "2021",
    company: "Tidal Park",
    email: "manoj123@gmail.com",
    skills: "C++,JAVA,PYTHON,C",
    eventsParticipated: "Smart india hackathon",
    platforms: "Leetcode,HackerRank,HackerEarth",
    achievements:
      "A Unicorn developer, first to be certified by TidalPark as Associate Android Developer in the world, Droidcon Speaker, a regular blogger at Medium and an open source contributor.Demonstrated the ability to handle both design and development in an efficient way. Accomplishments and Recognition, First to be certified as Android Developer by Tidalpark, Full Sponsorship by Tidalpark for io17, Droidcon Boston Speaker, GDG community Speaker, Mentor at Mindorks",
    contest: "LeetCode, CodingNinjas",
  },
  {
    id: "it6",
    src: require("./images/Abinath.jpg"),
    name: "Abinath",
    phone: "6384554049",
    location: "Salem",
    year: "2021",
    company: "Tidal Park",
    email: "manoj123@gmail.com",
    skills: "C++,JAVA,PYTHON,C",
    eventsParticipated: "Smart india hackathon",
    platforms: "Leetcode,HackerRank,HackerEarth",
    achievements:
      "A Unicorn developer, first to be certified by TidalPark as Associate Android Developer in the world, Droidcon Speaker, a regular blogger at Medium and an open source contributor.Demonstrated the ability to handle both design and development in an efficient way. Accomplishments and Recognition, First to be certified as Android Developer by Tidalpark, Full Sponsorship by Tidalpark for io17, Droidcon Boston Speaker, GDG community Speaker, Mentor at Mindorks",
    contest: "LeetCode, CodingNinjas",
  },
];
